<svelte:head>
	<title>Terms of Use — AI Governance Readiness Assessment</title>
</svelte:head>

<div class="max-w-3xl mx-auto py-8" data-testid="terms-page">
	<h1 class="text-3xl font-bold text-[var(--color-text-primary)] mb-2">Terms of Use</h1>
	<p class="text-sm text-[var(--color-text-muted)] mb-8">Effective April 11, 2026</p>

	<div class="space-y-8 text-sm text-[var(--color-text-secondary)] leading-relaxed">
		<section>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">About This Tool</h2>
			<p>
				The AI Governance Readiness Assessment ("the Tool") is a free, self-service assessment
				provided by Krystal Martinez. It evaluates organizational AI governance posture across five
				categories using self-reported responses and produces a scored dashboard with a downloadable
				PDF report.
			</p>
		</section>

		<section
			class="bg-[var(--color-risk-critical)]/5 border border-[var(--color-risk-critical)]/20 rounded-xl p-6"
		>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">
				Important Disclaimer
			</h2>
			<p class="mb-3">
				<strong class="text-[var(--color-text-primary)]"
					>This Tool is for informational purposes only and does not constitute legal, compliance,
					regulatory, or professional advice.</strong
				>
			</p>
			<ul class="list-disc pl-5 space-y-2">
				<li>
					Results reflect self-reported responses and have not been independently verified or
					audited.
				</li>
				<li>
					The Tool does not guarantee compliance with any regulation, including the EU AI Act,
					Colorado AI Act (SB 24-205), or any other jurisdiction's requirements.
				</li>
				<li>
					Regulatory requirements vary by jurisdiction, industry, organizational size, and the
					specific AI systems in use. This Tool cannot account for all variables.
				</li>
				<li>
					You should consult qualified legal, compliance, and security professionals before making
					governance decisions based on these results.
				</li>
			</ul>
		</section>

		<section>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">Acceptable Use</h2>
			<p>You may use the Tool for:</p>
			<ul class="list-disc pl-5 space-y-2 mt-2">
				<li>Internal organizational self-assessment</li>
				<li>Identifying potential governance gaps for further investigation</li>
				<li>Starting conversations with leadership and compliance teams</li>
				<li>Educational and research purposes</li>
			</ul>
			<p class="mt-3">You may not:</p>
			<ul class="list-disc pl-5 space-y-2 mt-2">
				<li>
					Represent assessment results as a certified audit, compliance certification, or legal
					opinion
				</li>
				<li>
					Use results to make representations to regulators about your compliance status without
					independent professional verification
				</li>
				<li>Redistribute or resell the Tool or its output as your own product</li>
			</ul>
		</section>

		<section>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">
				Limitation of Liability
			</h2>
			<p>
				The Tool is provided "as is" without warranties of any kind, express or implied. Krystal
				Martinez shall not be liable for any damages arising from the use of or inability to use the
				Tool, including but not limited to direct, indirect, incidental, consequential, or punitive
				damages. This includes any reliance on assessment results, recommendations, or regulatory
				deadline information provided by the Tool.
			</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">
				Regulatory References
			</h2>
			<p>
				The Tool references specific regulations including the EU AI Act (Regulation (EU)
				2024/1689), Colorado AI Act (SB 24-205), and the OWASP LLM Top 10 (2025). Regulatory
				deadlines and requirements cited in the Tool are based on publicly available information as
				of the date of publication. Regulations may be amended, delayed, or interpreted differently
				by enforcement authorities. Always verify current regulatory status with qualified legal
				counsel.
			</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">
				Intellectual Property
			</h2>
			<p>
				The Tool, including its assessment framework, scoring methodology, question content, and
				design, is the intellectual property of Krystal Martinez. The PDF reports generated by the
				Tool may be freely shared within your organization for internal governance purposes.
			</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">
				Changes to These Terms
			</h2>
			<p>
				These terms may be updated at any time. The effective date at the top of this page will
				reflect the most recent revision. Continued use of the Tool after changes constitutes
				acceptance of the updated terms.
			</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold text-[var(--color-text-primary)] mb-3">Contact</h2>
			<p>
				For questions about these terms, contact Krystal Martinez via <a
					href="https://governance.krystalmartinez.com"
					class="text-[var(--color-accent)] hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)] rounded"
					>governance.krystalmartinez.com</a
				>.
			</p>
		</section>
	</div>
</div>
